package com.maventest.mavens.frameworkCore;

public enum WaitType {
    WAITFORELEMENTTOBEEENABLED, 
    WAITFORELEMENTTOBEDISPLAYED, 
    WAITFORELEMENTTOBECLICKABLE, 
    WAITFORELEMENTTODISAPPEAR
}
